"""paper_trading_pnl_charges

Revision ID: 70abe2b278ea
Revises: c7c79a142e9b
Create Date: 2026-06-29 03:37:02.212666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70abe2b278ea'
down_revision: Union[str, None] = 'c7c79a142e9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('option_type', sa.String(length=2), nullable=True))
    op.add_column('trades', sa.Column('strike', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('lot_size', sa.Integer(), nullable=True))
    op.add_column('trades', sa.Column('expiry_date', sa.String(length=10), nullable=True))
    op.add_column('trades', sa.Column('expiry_display', sa.String(length=30), nullable=True))
    op.add_column('trades', sa.Column('instrument_token', sa.BigInteger(), nullable=True))
    op.add_column('trades', sa.Column('direction', sa.String(length=10), nullable=True))
    op.add_column('trades', sa.Column('current_price', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('target_price', sa.Float(), nullable=True, server_default='0'))
    op.add_column('trades', sa.Column('gross_pnl', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('unrealized_pnl', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('realized_pnl', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('charges_total', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('charges_brokerage', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('charges_stt', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('charges_txn', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('charges_gst', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('charges_sebi', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('charges_stamp', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('charges_entry', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('last_mtm_at', sa.DateTime(), nullable=True))
    op.add_column('trades', sa.Column('notes', sa.Text(), nullable=True))
    op.drop_column('trades', 'target')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('target', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('trades', 'notes')
    op.drop_column('trades', 'last_mtm_at')
    op.drop_column('trades', 'charges_entry')
    op.drop_column('trades', 'charges_stamp')
    op.drop_column('trades', 'charges_sebi')
    op.drop_column('trades', 'charges_gst')
    op.drop_column('trades', 'charges_txn')
    op.drop_column('trades', 'charges_stt')
    op.drop_column('trades', 'charges_brokerage')
    op.drop_column('trades', 'charges_total')
    op.drop_column('trades', 'realized_pnl')
    op.drop_column('trades', 'unrealized_pnl')
    op.drop_column('trades', 'gross_pnl')
    op.drop_column('trades', 'target_price')
    op.drop_column('trades', 'current_price')
    op.drop_column('trades', 'direction')
    op.drop_column('trades', 'instrument_token')
    op.drop_column('trades', 'expiry_display')
    op.drop_column('trades', 'expiry_date')
    op.drop_column('trades', 'lot_size')
    op.drop_column('trades', 'strike')
    op.drop_column('trades', 'option_type')
    # ### end Alembic commands ###
