"""add_expiry_columns_to_signals

Revision ID: c7c79a142e9b
Revises: 
Create Date: 2026-06-29 02:10:45.514004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7c79a142e9b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signals', sa.Column('expiry_date_iso', sa.String(length=10), nullable=True))
    op.add_column('signals', sa.Column('expiry_display', sa.String(length=30), nullable=True))
    op.add_column('signals', sa.Column('expiry_dte', sa.Integer(), nullable=True))
    op.add_column('signals', sa.Column('expiry_series', sa.String(length=10), nullable=True))
    op.create_foreign_key(None, 'trades', 'signals', ['signal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_column('signals', 'expiry_series')
    op.drop_column('signals', 'expiry_dte')
    op.drop_column('signals', 'expiry_display')
    op.drop_column('signals', 'expiry_date_iso')
    # ### end Alembic commands ###
